### PR TITLE
translated README.md to portuguese

### PR DESCRIPTION
**Pull request by BeatrizHerculano**
---
name: 🦁 Document Translation to Portuguese
about: I translated the Readme.md file to Portuguese, on a new file, inside the doc/pt-br folder.
title: ""
labels: "Status: Review Needed"
assignees: ""
---

## Issue it resolves

**URL:**

https://github.com/armirage/grunt-remove-js-comments/issues/1
**Type:**

- [ ] Type: Bug
- [X] Type: Documentation
- [ ] Type: Enhancement
- [ ] Type: Maintenance

## Your Solution

**Description:**

I freely translated the documentation for this project, i am a native speaker for Portuguese and i have a fluent english, but there was a moment i was confused with a text, it is in the line 321 of the README.md file. If you find that my translation needs improving ,just contact me 😄 .

## Checklist:

- [X] I followed the Armirage style guidelines using the ESLint Sharable Config
- [X] I performed a self-review ensuring the code is understandable with descriptive names
- [X] I commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by ClintMulligan — CHANGES_REQUESTED** [review]
Beatrix this looks amazing! I have a few questions..

1. I saw you changed the English README.md, Such as changing - into *, why is that?
2. The translation should be named README.pt.md and a relative link to it added in ..docs/l10n/index.md The world at the top links to that index page of different translations.
3. As such that top line 3 in your "Portuguese" version should read "Portuguese" not "English".
4. And I want to give you credit for the hard work. In the Acknowledgment parts of both English and Portuguese versions.. we should add something like:

Thank you to [BeatrizHerculano](https://github.com/BeatrizHerculano) BeatrizHerculano for translating this [README into Portuguese.](https://github.com/armirage/grunt-remove-js-comments/blob/master/docs/l10n/README.pt.md)

Thanks talk to you later.

**Comment by ClintMulligan** [comment]
Beatrix this looks amazing! I have a few questions..

1. I saw you changed the English README.md, Such as changing - into *, why is that?
2. The translation should be named README.pt.md and a relative link to it added in ..docs/l10n/index.md The world at the top links to that index page of different translations.
3. As such that top line 3 in your "Portuguese" version should read "Portuguese" not "English".
4. And I want to give you credit for the hard work. In the Acknowledgment parts of both English and Portuguese versions.. we should add something like:

Thank you to [BeatrizHerculano](https://github.com/BeatrizHerculano) BeatrizHerculano for translating this [README into Portuguese.](https://github.com/armirage/grunt-remove-js-comments/blob/master/docs/l10n/README.pt.md)

Thanks talk to you later.

**Comment by BeatrizHerculano** [comment]
> Beatrix this looks amazing! I have a few questions..
> 
> 1. I saw you changed the English README.md, Such as changing - into *, why is that?
> 2. The translation should be named README.pt.md and a relative link to it added in ..docs/l10n/index.md The world at the top links to that index page of different translations.
> 3. As such that top line 3 in your "Portuguese" version should read "Portuguese" not "English".
> 4. And I want to give you credit for the hard work. In the Acknowledgment parts of both English and Portuguese versions.. we should add something like:
> 
> Thank you to [BeatrizHerculano](https://github.com/BeatrizHerculano) BeatrizHerculano for translating this [README into Portuguese.](https://github.com/armirage/grunt-remove-js-comments/blob/master/docs/l10n/README.pt.md)
> 
> Thanks talk to you later.

Hey about changing the README.md, i added a note for the Portuguese documentation on the line 39, the others changes problaby were made by my linter, sorry i should've checked for this type of changes before summiting my PR.  For the topics remaining i will submit a fix for them soon.

Thanks 😄

**Review by ClintMulligan — APPROVED** [review]
I will push the request and can make any minor changes from here Thank you!

**Comment by ClintMulligan** [comment]
Add translation to Portuguese

**Pull request merged**
